#!/usr/bin/env bash
# NetClaw installer — pure-bash TUI: logo, arrow-key menu, multi-select checklist.
# No external dependencies (no whiptail/dialog). Degrades to plain output when
# stdout is not a TTY.

# ── colors (VibeOps neon palette — vibeopsforum.com) ─────────────
T_PINK='\033[38;5;198m'      # neon pink   (#ff2d9f)
T_PINKLT='\033[38;5;212m'    # light pink  (#ff9bd2)
T_CYAN='\033[38;5;45m'       # neon cyan   (#38e8ff)
T_CYANLT='\033[38;5;159m'    # pale cyan   (#b9f7ff)
T_YELLOW='\033[38;5;228m'    # neon yellow (#f6ff6a)
T_WHITE='\033[97m'
T_BOLD='\033[1m'
T_DIM='\033[2m'
T_REV='\033[7m'
T_NC='\033[0m'

tui_is_tty() { [ -t 0 ] && [ -t 1 ]; }

# ── logo ─────────────────────────────────────────────────────────
# ANSI half-block rendering of netclaw.jpg — the lobster with its CCIE badge
# grabbing network cables running into the switch stack. Generated by
# lib/make-logo-art.py into lib/netclaw-logo.ans; shown on 256-color
# terminals, with a plain wordmark fallback everywhere else.
NETCLAW_LOGO_ANS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/netclaw-logo.ans"

netclaw_logo() {
    local c="$T_CYAN" y="$T_YELLOW" d="$T_DIM" b="$T_BOLD" n="$T_NC"
    echo ""
    if [ -f "$NETCLAW_LOGO_ANS" ] && [ "$(tput colors 2>/dev/null || echo 8)" -ge 256 ]; then
        cat "$NETCLAW_LOGO_ANS"
        echo ""
    fi
    echo -e "${c}      ███╗   ██╗███████╗████████╗ ██████╗██╗      █████╗ ██╗    ██╗${n}"
    echo -e "${c}      ████╗  ██║██╔════╝╚══██╔══╝██╔════╝██║     ██╔══██╗██║    ██║${n}"
    echo -e "${c}      ██╔██╗ ██║█████╗     ██║   ██║     ██║     ███████║██║ █╗ ██║${n}"
    echo -e "${c}      ██║╚██╗██║██╔══╝     ██║   ██║     ██║     ██╔══██║██║███╗██║${n}"
    echo -e "${c}      ██║ ╚████║███████╗   ██║   ╚██████╗███████╗██║  ██║╚███╔███╔╝${n}"
    echo -e "${c}      ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝ ${n}"
    echo ""
    echo -e "${y}${b}      An AI agent that claws through your network.${n}"
    echo -e "${d}      CCIE AI0001 AGENT  ·  automateyournetwork/netclaw  ·  vibeopsforum.com${n}"
    echo ""
}

# ── key reader: echoes "up" "down" "left" "right" "space" "enter" ──
# "all" "none" "quit" or the raw char
tui_read_key() {
    local k rest
    IFS= read -rsn1 k
    if [ "$k" = $'\x1b' ]; then
        read -rsn2 -t 0.05 rest || rest=""
        case "$rest" in
            '[A') echo up ;;
            '[B') echo down ;;
            '[C') echo right ;;
            '[D') echo left ;;
            *)    echo esc ;;
        esac
    else
        case "$k" in
            "")      echo enter ;;
            " ")     echo space ;;
            k|K)     echo up ;;
            j|J)     echo down ;;
            a|A)     echo all ;;
            n|N)     echo none ;;
            q|Q)     echo quit ;;
            *)       echo "$k" ;;
        esac
    fi
}

_tui_cleanup() { printf '\033[?25h'; stty echo 2>/dev/null || true; }

# ── single-select menu ───────────────────────────────────────────
# tui_menu "Title" "opt1" "opt2" ...  → sets TUI_CHOICE to selected index (0-based)
# returns 1 if aborted
tui_menu() {
    local title="$1"; shift
    local opts=("$@") cur=0 i key
    TUI_CHOICE=-1

    if ! tui_is_tty; then
        # non-interactive: pick the first option
        TUI_CHOICE=0
        return 0
    fi

    trap _tui_cleanup EXIT
    printf '\033[?25l'
    echo -e "  ${T_BOLD}${title}${T_NC}"
    echo -e "  ${T_DIM}↑/↓ move · Enter select · q quit${T_NC}"
    echo ""
    # reserve lines
    for i in "${!opts[@]}"; do echo ""; done
    while true; do
        printf '\033[%dA' "${#opts[@]}"
        for i in "${!opts[@]}"; do
            printf '\033[2K'
            if [ "$i" -eq "$cur" ]; then
                echo -e "   ${T_PINK}${T_BOLD}❯ ${opts[$i]}${T_NC}"
            else
                echo -e "     ${opts[$i]}"
            fi
        done
        key=$(tui_read_key)
        case "$key" in
            up)    cur=$(( (cur + ${#opts[@]} - 1) % ${#opts[@]} )) ;;
            down)  cur=$(( (cur + 1) % ${#opts[@]} )) ;;
            enter) TUI_CHOICE=$cur; printf '\033[?25h'; echo ""; return 0 ;;
            quit|esc) printf '\033[?25h'; echo ""; return 1 ;;
        esac
    done
}

# ── multi-select checklist with category headers + scrolling ─────
# Input arrays (set by caller):
#   CL_IDS[i]    component id, or "" for a category-header row
#   CL_LABELS[i] display text
#   CL_ON[i]     1 = preselected
# Output: TUI_SELECTED = space-separated ids. Returns 1 if aborted.
tui_checklist() {
    local title="$1"
    local total=${#CL_LABELS[@]}
    local cur=0 top=0 i key rows view
    TUI_SELECTED=""

    if ! tui_is_tty; then
        for i in $(seq 0 $((total - 1))); do
            [ -n "${CL_IDS[$i]}" ] && [ "${CL_ON[$i]}" = "1" ] && TUI_SELECTED="$TUI_SELECTED ${CL_IDS[$i]}"
        done
        TUI_SELECTED="${TUI_SELECTED# }"
        return 0
    fi

    # first selectable row
    while [ -z "${CL_IDS[$cur]}" ] && [ "$cur" -lt $((total - 1)) ]; do cur=$((cur + 1)); done

    rows=$(tput lines 2>/dev/null || echo 24)
    view=$((rows - 9)); [ "$view" -lt 5 ] && view=5; [ "$view" -gt "$total" ] && view=$total

    trap _tui_cleanup EXIT
    printf '\033[?25l'
    echo -e "  ${T_BOLD}${title}${T_NC}"
    echo -e "  ${T_DIM}↑/↓ move · Space toggle · a all · n none · Enter confirm · q cancel${T_NC}"
    echo ""
    for i in $(seq 1 $((view + 1))); do echo ""; done

    while true; do
        # keep cursor in viewport
        [ "$cur" -lt "$top" ] && top=$cur
        [ "$cur" -ge $((top + view)) ] && top=$((cur - view + 1))

        printf '\033[%dA' $((view + 1))
        local idx line mark count=0 sel=0
        for i in $(seq 0 $((total - 1))); do
            [ -n "${CL_IDS[$i]}" ] && { count=$((count + 1)); [ "${CL_ON[$i]}" = "1" ] && sel=$((sel + 1)); }
        done
        for line in $(seq 0 $((view - 1))); do
            idx=$((top + line))
            printf '\033[2K'
            if [ "$idx" -ge "$total" ]; then echo ""; continue; fi
            if [ -z "${CL_IDS[$idx]}" ]; then
                echo -e "  ${T_PINK}${T_BOLD}${CL_LABELS[$idx]}${T_NC}"
            else
                [ "${CL_ON[$idx]}" = "1" ] && mark="${T_PINK}[x]${T_NC}" || mark="[ ]"
                if [ "$idx" -eq "$cur" ]; then
                    echo -e "   ${T_PINK}${T_BOLD}❯${T_NC} $mark ${T_BOLD}${CL_LABELS[$idx]}${T_NC}"
                else
                    echo -e "     $mark ${CL_LABELS[$idx]}"
                fi
            fi
        done
        printf '\033[2K'
        echo -e "  ${T_DIM}${sel}/${count} selected · showing $((top + 1))-$(( top + view > total ? total : top + view )) of ${total}${T_NC}"

        key=$(tui_read_key)
        case "$key" in
            up)
                i=$((cur - 1))
                while [ "$i" -ge 0 ] && [ -z "${CL_IDS[$i]}" ]; do i=$((i - 1)); done
                [ "$i" -ge 0 ] && cur=$i ;;
            down)
                i=$((cur + 1))
                while [ "$i" -lt "$total" ] && [ -z "${CL_IDS[$i]}" ]; do i=$((i + 1)); done
                [ "$i" -lt "$total" ] && cur=$i ;;
            space)
                [ "${CL_ON[$cur]}" = "1" ] && CL_ON[$cur]=0 || CL_ON[$cur]=1 ;;
            all)
                for i in $(seq 0 $((total - 1))); do [ -n "${CL_IDS[$i]}" ] && CL_ON[$i]=1; done ;;
            none)
                for i in $(seq 0 $((total - 1))); do [ -n "${CL_IDS[$i]}" ] && CL_ON[$i]=0; done ;;
            enter)
                for i in $(seq 0 $((total - 1))); do
                    [ -n "${CL_IDS[$i]}" ] && [ "${CL_ON[$i]}" = "1" ] && TUI_SELECTED="$TUI_SELECTED ${CL_IDS[$i]}"
                done
                TUI_SELECTED="${TUI_SELECTED# }"
                printf '\033[?25h'; echo ""
                return 0 ;;
            quit|esc)
                printf '\033[?25h'; echo ""
                return 1 ;;
        esac
    done
}

# ── yes/no prompt (TTY-aware, default-able) ──────────────────────
tui_yesno() {
    local prompt="$1" default="${2:-n}" yn
    if ! tui_is_tty; then [ "$default" = "y" ]; return; fi
    if [ "$default" = "y" ]; then
        echo -ne "  ${T_CYAN}${prompt}${T_NC} ${T_DIM}[Y/n]${T_NC}: "
    else
        echo -ne "  ${T_CYAN}${prompt}${T_NC} ${T_DIM}[y/N]${T_NC}: "
    fi
    read -r yn
    yn="${yn:-$default}"
    [[ "$yn" =~ ^[Yy] ]]
}
